name: Deploy to azure app service

    
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  AZURE_WEBAPP_NAME: webapprpdemo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration release
      
    - name: Publish
      run: dotnet publish -c Release -o '${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp'
      
    - name: Deploy
      uses: Azure/webapps-deploy@v2
      with: 
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        slot-name: 'development'
        publish-profile: ${{secrets.AZUREWEBAPPSECRET}}
        package: '${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp'
        
